const AccountOfficer = require("../models/AccountOfficer");
const AuditLog = require("../models/AuditLog");
const User = require("../models/User");
const { validatePasswordStrength, generateTempPassword } = require("../lib/password");
const { sendTempPasswordEmail } = require("./c_users");

function fail(res, label, error) {
  console.error(`${label} error:`, error);
  const duplicate = /unique|duplicate/i.test(error?.message || "");
  return res.status(duplicate ? 409 : 500).json({
    success: false,
    message: duplicate ? "That username or email is already in use." : error.message || "Internal server error",
  });
}

function audit(req, action, id, details) {
  return AuditLog.record({
    actorId: req.user?.id,
    actorUsername: req.user?.username,
    action,
    entityType: "user",
    entityId: id,
    details,
    ipAddress: req.ip,
  });
}

exports.list = async (req, res) => {
  try {
    return res.json({ success: true, data: await AccountOfficer.listAccountOfficers() });
  } catch (error) {
    return fail(res, "List account officers", error);
  }
};

exports.create = async (req, res) => {
  try {
    const { username, email, phone, full_name, password, department_id } = req.body || {};
    if (!String(full_name || "").trim()) return res.status(400).json({ success: false, message: "full_name is required" });
    if (!String(username || "").trim()) return res.status(400).json({ success: false, message: "username is required" });
    if (!String(email || "").trim()) return res.status(400).json({ success: false, message: "email is required" });
    if (!Number(department_id)) return res.status(400).json({ success: false, message: "department is required" });

    // Same convention as User Management: no password supplied -> generate one and email it.
    const autoGenerate = !password;
    let effectivePassword = password;
    if (autoGenerate) {
      effectivePassword = generateTempPassword();
    } else {
      const passwordError = validatePasswordStrength(password);
      if (passwordError) return res.status(400).json({ success: false, message: passwordError });
    }

    const row = await AccountOfficer.createAccountOfficer({
      username: String(username).trim(),
      email: String(email).trim(),
      phone,
      full_name: String(full_name).trim(),
      password: effectivePassword,
      department_id,
    });

    let mailResult = { sent: false };
    if (autoGenerate && row) {
      await User.setMustChangePassword(row.id, true);
      mailResult = await sendTempPasswordEmail({
        to: row.email,
        name: row.full_name || row.username,
        username: row.username,
        tempPassword: effectivePassword,
        isNewAccount: true,
      });
    }

    await audit(req, "USER_CREATED", row?.id, {
      username: row?.username,
      role: "ACCOUNT OFFICER",
      department_id: Number(department_id),
      autoGeneratedPassword: autoGenerate,
      emailSent: mailResult.sent,
    });
    return res.status(201).json({
      success: true,
      data: row,
      message: autoGenerate
        ? mailResult.sent
          ? `A temporary password was emailed to ${row.email}.`
          : "Account created, but the email could not be sent (SMTP isn't configured on this server) — check the server console for the temporary password."
        : undefined,
    });
  } catch (error) {
    return fail(res, "Create account officer", error);
  }
};

exports.update = async (req, res) => {
  try {
    const id = Number(req.params.id);
    if (!Number.isFinite(id)) return res.status(400).json({ success: false, message: "Invalid id" });
    const { username, email, phone, full_name, department_id } = req.body || {};
    if (email !== undefined && !String(email || "").trim()) {
      return res.status(400).json({ success: false, message: "email is required" });
    }
    if (department_id !== undefined && !Number(department_id)) {
      return res.status(400).json({ success: false, message: "department is required" });
    }
    const row = await AccountOfficer.updateAccountOfficer(id, {
      username: username !== undefined ? String(username).trim() : undefined,
      email: email !== undefined ? String(email).trim() : undefined,
      phone,
      full_name: full_name !== undefined ? String(full_name).trim() : undefined,
      department_id,
    });
    if (!row) return res.status(404).json({ success: false, message: "Account officer not found" });
    await audit(req, "USER_UPDATED", id, { username: row?.username, fields: Object.keys(req.body || {}), via: "account-officers" });
    return res.json({ success: true, data: row });
  } catch (error) {
    return fail(res, "Update account officer", error);
  }
};

exports.deactivate = async (req, res) => {
  try {
    const id = Number(req.params.id);
    if (!Number.isFinite(id)) return res.status(400).json({ success: false, message: "Invalid id" });
    const row = await AccountOfficer.deactivateAccountOfficer(id);
    if (!row) return res.status(404).json({ success: false, message: "Account officer not found" });
    await audit(req, "USER_DEACTIVATED", id, { username: row?.username });
    return res.json({ success: true, data: row });
  } catch (error) {
    return fail(res, "Deactivate account officer", error);
  }
};

exports.reactivate = async (req, res) => {
  try {
    const id = Number(req.params.id);
    if (!Number.isFinite(id)) return res.status(400).json({ success: false, message: "Invalid id" });
    const row = await AccountOfficer.reactivateAccountOfficer(id);
    if (!row) return res.status(404).json({ success: false, message: "Account officer not found" });
    await audit(req, "USER_REACTIVATED", id, { username: row?.username });
    return res.json({ success: true, data: row });
  } catch (error) {
    return fail(res, "Reactivate account officer", error);
  }
};
