const User = require("../models/User");
const AuditLog = require("../models/AuditLog");
const Proponent = require("../models/Proponent");
const Notification = require("../models/Notification");
const ActivityLog = require("../models/ActivityLog");
const { validatePasswordStrength, generateTempPassword } = require("../lib/password");
const { sendMail } = require("../lib/mailer");

/** Shared by account creation (no admin-chosen password) and admin-triggered
 * reset — same email either way, since both hand the owner a one-time temp
 * password they're required to replace on first login. Includes the
 * username (the password alone isn't enough to sign in) and a direct link
 * to the portal. */
function sendTempPasswordEmail({ to, name, username, tempPassword, isNewAccount }) {
  const intro = isNewAccount
    ? "An account was created for you on the 3CORE Locator Portal."
    : "An administrator reset your password.";
  const loginUrl = `${String(process.env.FRONTEND_URL || "").replace(/\/+$/, "")}/`;
  return sendMail({
    to,
    subject: isNewAccount ? "Your 3CORE Locator Portal account" : "Your 3CORE Locator Portal password was reset",
    text:
      `Hello ${name},\n\n${intro}\n\n` +
      `Username: ${username}\n` +
      `Temporary password: ${tempPassword}\n\n` +
      `Sign in here: ${loginUrl}\n\n` +
      `You'll be asked to set a new password right away. If you didn't expect this, contact 3CORE.\n`,
    html:
      `<p>Hello ${name},</p>` +
      `<p>${intro}</p>` +
      `<p>Username: <b>${username}</b><br/>` +
      `Temporary password: <span style="font-size:18px;font-weight:bold;letter-spacing:1px;">${tempPassword}</span></p>` +
      `<p><a href="${loginUrl}" style="display:inline-block;padding:10px 18px;background:#111827;color:#fff;text-decoration:none;border-radius:6px;">Sign in to the portal</a></p>` +
      `<p>You'll be asked to set a new password right away. If you didn't expect this, contact 3CORE.</p>`,
  });
}

exports.list = async (req, res) => {
  try {
    const rows = await User.listUsers();
    return res.json({ success: true, data: rows });
  } catch (error) {
    console.error("List users error:", error);
    return res.status(500).json({ success: false, message: error.message || "Internal server error" });
  }
};

exports.getById = async (req, res) => {
  try {
    const id = Number(req.params.id);
    if (!Number.isFinite(id)) return res.status(400).json({ success: false, message: "Invalid id" });

    const row = await User.getUserById(id);
    if (!row) return res.status(404).json({ success: false, message: "User not found" });

    return res.json({ success: true, data: row });
  } catch (error) {
    console.error("Get user error:", error);
    return res.status(500).json({ success: false, message: error.message || "Internal server error" });
  }
};

exports.create = async (req, res) => {
  try {
    const { username, email, phone, full_name, password, is_active, role_id } = req.body || {};
    if (!username) return res.status(400).json({ success: false, message: "username is required" });
    if (!String(email || "").trim()) return res.status(400).json({ success: false, message: "email is required" });

    // No password supplied (e.g. Locator Accounts' create form, which never
    // shows a password field) — generate one, email it, and require the
    // owner to replace it on first login instead of an admin picking it.
    const autoGenerate = !password;
    let effectivePassword = password;
    if (autoGenerate) {
      effectivePassword = generateTempPassword();
    } else {
      const passwordError = validatePasswordStrength(password);
      if (passwordError) return res.status(400).json({ success: false, message: passwordError });
    }

    const row = await User.createUser({ username, email, phone, full_name, password: effectivePassword, is_active, role_id });

    let mailResult = { sent: false };
    if (autoGenerate && row) {
      await User.setMustChangePassword(row.id, true);
      mailResult = await sendTempPasswordEmail({
        to: row.email,
        name: row.full_name || row.username,
        username: row.username,
        tempPassword: effectivePassword,
        isNewAccount: true,
      });
    }

    await AuditLog.record({
      actorId: req.user?.id,
      actorUsername: req.user?.username,
      action: "USER_CREATED",
      entityType: "user",
      entityId: row?.id,
      details: { username: row?.username, role_id, autoGeneratedPassword: autoGenerate, emailSent: mailResult.sent },
      ipAddress: req.ip,
    });
    return res.status(201).json({
      success: true,
      data: row,
      emailSent: autoGenerate ? mailResult.sent : undefined,
      message: autoGenerate
        ? mailResult.sent
          ? `A temporary password was emailed to ${row.email}.`
          : `Account created, but the email could not be sent (SMTP isn't configured on this server) — check the server console for the temporary password.`
        : undefined,
    });
  } catch (error) {
    console.error("Create user error:", error);
    return res.status(500).json({ success: false, message: error.message || "Internal server error" });
  }
};

exports.update = async (req, res) => {
  try {
    const id = Number(req.params.id);
    if (!Number.isFinite(id)) return res.status(400).json({ success: false, message: "Invalid id" });

    const { username, email, phone, full_name, password, is_active, role_id } = req.body || {};
    if (email !== undefined && !String(email || "").trim()) {
      return res.status(400).json({ success: false, message: "email is required" });
    }
    if (password) {
      const passwordError = validatePasswordStrength(password);
      if (passwordError) return res.status(400).json({ success: false, message: passwordError });
    }
    const row = await User.updateUser(id, { username, email, phone, full_name, password, is_active, role_id });
    if (!row) return res.status(404).json({ success: false, message: "User not found" });

    await AuditLog.record({
      actorId: req.user?.id,
      actorUsername: req.user?.username,
      action: password ? "USER_PASSWORD_RESET" : "USER_UPDATED",
      entityType: "user",
      entityId: id,
      details: { fields: Object.keys(req.body || {}) },
      ipAddress: req.ip,
    });

    // Proponent-facing "Password changed" activity entry.
    if (password !== undefined && String(password).trim() !== "") {
      const prop = await Proponent.getProponentByUserId(id);
      ActivityLog.record({
        actorUserId: req.user?.id ?? null,
        proponentId: prop?.id ?? null,
        entityType: "USER",
        entityId: id,
        action: "PASSWORD_CHANGED",
        ip: req.ip,
      });
    }

    return res.json({ success: true, data: row });
  } catch (error) {
    console.error("Update user error:", error);
    return res.status(500).json({ success: false, message: error.message || "Internal server error" });
  }
};

exports.deactivate = async (req, res) => {
  try {
    const id = Number(req.params.id);
    if (!Number.isFinite(id)) return res.status(400).json({ success: false, message: "Invalid id" });

    const row = await User.deactivateUser(id);
    if (!row) return res.status(404).json({ success: false, message: "User not found" });
    await AuditLog.record({
      actorId: req.user?.id,
      actorUsername: req.user?.username,
      action: "USER_DEACTIVATED",
      entityType: "user",
      entityId: id,
      ipAddress: req.ip,
    });
    return res.json({ success: true, data: row });
  } catch (error) {
    console.error("Deactivate user error:", error);
    return res.status(500).json({ success: false, message: error.message || "Internal server error" });
  }
};

exports.reactivate = async (req, res) => {
  try {
    const id = Number(req.params.id);
    if (!Number.isFinite(id)) return res.status(400).json({ success: false, message: "Invalid id" });

    const row = await User.reactivateUser(id);
    if (!row) return res.status(404).json({ success: false, message: "User not found" });
    await AuditLog.record({
      actorId: req.user?.id,
      actorUsername: req.user?.username,
      action: "USER_REACTIVATED",
      entityType: "user",
      entityId: id,
      ipAddress: req.ip,
    });
    return res.json({ success: true, data: row });
  } catch (error) {
    console.error("Reactivate user error:", error);
    return res.status(500).json({ success: false, message: error.message || "Internal server error" });
  }
};

/** Distinct from deactivate: an easily-reversed hold, not a long-term closure. */
exports.suspend = async (req, res) => {
  try {
    const id = Number(req.params.id);
    if (!Number.isFinite(id)) return res.status(400).json({ success: false, message: "Invalid id" });

    const row = await User.suspendUser(id);
    if (!row) return res.status(404).json({ success: false, message: "User not found" });
    await AuditLog.record({
      actorId: req.user?.id,
      actorUsername: req.user?.username,
      action: "USER_SUSPENDED",
      entityType: "user",
      entityId: id,
      ipAddress: req.ip,
    });
    return res.json({ success: true, data: row });
  } catch (error) {
    console.error("Suspend user error:", error);
    return res.status(500).json({ success: false, message: error.message || "Internal server error" });
  }
};

exports.unsuspend = async (req, res) => {
  try {
    const id = Number(req.params.id);
    if (!Number.isFinite(id)) return res.status(400).json({ success: false, message: "Invalid id" });

    const row = await User.unsuspendUser(id);
    if (!row) return res.status(404).json({ success: false, message: "User not found" });
    await AuditLog.record({
      actorId: req.user?.id,
      actorUsername: req.user?.username,
      action: "USER_UNSUSPENDED",
      entityType: "user",
      entityId: id,
      ipAddress: req.ip,
    });
    return res.json({ success: true, data: row });
  } catch (error) {
    console.error("Unsuspend user error:", error);
    return res.status(500).json({ success: false, message: error.message || "Internal server error" });
  }
};

/** Forces the user to log in again everywhere, without waiting for their
 * current JWT's 24h expiry — e.g. after a suspected compromise. */
exports.revokeSessions = async (req, res) => {
  try {
    const id = Number(req.params.id);
    if (!Number.isFinite(id)) return res.status(400).json({ success: false, message: "Invalid id" });

    const row = await User.revokeSessions(id);
    if (!row) return res.status(404).json({ success: false, message: "User not found" });
    await AuditLog.record({
      actorId: req.user?.id,
      actorUsername: req.user?.username,
      action: "USER_SESSIONS_REVOKED",
      entityType: "user",
      entityId: id,
      ipAddress: req.ip,
    });
    return res.json({ success: true, data: row });
  } catch (error) {
    console.error("Revoke sessions error:", error);
    return res.status(500).json({ success: false, message: error.message || "Internal server error" });
  }
};

/** Admin "reset password": generates a temp password, emails it to the
 * user, and flags the account so Auth.js forces them onto a new password
 * before their next login completes. Also revokes any session still open
 * on the old password (User.adminResetPassword bumps token_version). */
exports.resetPassword = async (req, res) => {
  try {
    const id = Number(req.params.id);
    if (!Number.isFinite(id)) return res.status(400).json({ success: false, message: "Invalid id" });

    const user = await User.getUserById(id);
    if (!user) return res.status(404).json({ success: false, message: "User not found" });
    if (!user.email) {
      return res.status(400).json({ success: false, message: "This account has no email on file to send the new password to." });
    }

    const tempPassword = generateTempPassword();
    await User.adminResetPassword(id, tempPassword);

    const mailResult = await sendTempPasswordEmail({
      to: user.email,
      name: user.full_name || user.username,
      username: user.username,
      tempPassword,
      isNewAccount: false,
    });

    await AuditLog.record({
      actorId: req.user?.id,
      actorUsername: req.user?.username,
      action: "USER_PASSWORD_RESET",
      entityType: "user",
      entityId: id,
      details: { emailSent: mailResult.sent },
      ipAddress: req.ip,
    });
    ActivityLog.record({
      actorUserId: req.user?.id ?? null,
      proponentId: (await Proponent.getProponentByUserId(id))?.id ?? null,
      entityType: "USER",
      entityId: id,
      action: "PASSWORD_CHANGED",
      ip: req.ip,
    });

    return res.json({
      success: true,
      emailSent: mailResult.sent,
      message: mailResult.sent
        ? `A new temporary password was emailed to ${user.email}.`
        : `Password reset, but the email could not be sent (SMTP isn't configured on this server) — check the server console for the temporary password.`,
    });
  } catch (error) {
    console.error("Reset password error:", error);
    return res.status(500).json({ success: false, message: error.message || "Internal server error" });
  }
};

// --- Self-service registration review ---

exports.approve = async (req, res) => {
  try {
    const id = Number(req.params.id);
    if (!Number.isFinite(id)) return res.status(400).json({ success: false, message: "Invalid id" });

    const user = await User.getUserById(id);
    if (!user) return res.status(404).json({ success: false, message: "User not found" });
    if (user.status === "ACTIVE") {
      return res.status(400).json({ success: false, message: "This account is already active." });
    }

    const updated = await User.setUserStatus(id, "ACTIVE");
    await Proponent.setActiveByUserId(id, 1, req.user?.id ?? null);

    const approvedProponent = await Proponent.getProponentByUserId(id);
    await AuditLog.record({
      actorId: req.user?.id,
      actorUsername: req.user?.username,
      action: "USER_APPROVED",
      entityType: "user",
      entityId: id,
      ipAddress: req.ip,
    });
    ActivityLog.record({
      actorUserId: req.user?.id ?? null,
      proponentId: approvedProponent?.id ?? null,
      entityType: "USER",
      entityId: id,
      action: "ACCOUNT_APPROVED",
      ip: req.ip,
    });

    try {
      await Notification.createNotification({
        userId: id,
        subject: "Your CIAC account has been approved",
        body: "Your registration was approved. You can now sign in to the proponent portal.",
        createdBy: req.user?.id ?? null,
        eventType: "application_status",
      });
    } catch (notifyError) {
      console.error("Approve notification error:", notifyError);
    }

    return res.json({ success: true, data: updated });
  } catch (error) {
    console.error("Approve user error:", error);
    return res.status(500).json({ success: false, message: error.message || "Internal server error" });
  }
};

exports.reject = async (req, res) => {
  try {
    const id = Number(req.params.id);
    if (!Number.isFinite(id)) return res.status(400).json({ success: false, message: "Invalid id" });

    const note = String(req.body?.note ?? "").trim().slice(0, 500) || null;

    const user = await User.getUserById(id);
    if (!user) return res.status(404).json({ success: false, message: "User not found" });

    const updated = await User.setUserStatus(id, "REJECTED", note);
    await Proponent.setActiveByUserId(id, 0, req.user?.id ?? null);

    await AuditLog.record({
      actorId: req.user?.id,
      actorUsername: req.user?.username,
      action: "USER_REJECTED",
      entityType: "user",
      entityId: id,
      details: note ? { note } : undefined,
      ipAddress: req.ip,
    });
    ActivityLog.record({
      actorUserId: req.user?.id ?? null,
      entityType: "USER",
      entityId: id,
      action: "ACCOUNT_REJECTED",
      meta: note ? { note } : null,
      ip: req.ip,
    });

    return res.json({ success: true, data: updated });
  } catch (error) {
    console.error("Reject user error:", error);
    return res.status(500).json({ success: false, message: error.message || "Internal server error" });
  }
};

// --- Two-factor (Google Authenticator / TOTP) ---
// Users self-enroll on their next login; admins can only reset a lost
// authenticator, which clears it and forces re-enrollment.

exports.resetTotp = async (req, res) => {
  try {
    const id = Number(req.params.id);
    if (!Number.isFinite(id)) return res.status(400).json({ success: false, message: "Invalid id" });

    const record = await User.getTotpRecord(id);
    if (!record) return res.status(404).json({ success: false, message: "User not found" });

    await User.disableTotp(id);
    await AuditLog.record({
      actorId: req.user?.id,
      actorUsername: req.user?.username,
      action: "USER_TOTP_RESET",
      entityType: "user",
      entityId: id,
      ipAddress: req.ip,
    });
    return res.json({ success: true, data: { enabled: false } });
  } catch (error) {
    console.error("Reset TOTP error:", error);
    return res.status(500).json({ success: false, message: error.message || "Internal server error" });
  }
};
