const PDFDocument = require("pdfkit");

const PERMIT_TYPE_LABELS = {
  ENVIRONMENTAL: "Environmental Permit",
  FIRE: "Fire Safety Permit",
  OCCUPANCY: "Occupancy Permit",
  SANITARY: "Sanitary Permit",
  AUTHORITY_TO_OPERATE: "Authority to Operate",
};

function permitTypeLabel(type) {
  return PERMIT_TYPE_LABELS[String(type || "").toUpperCase()] || String(type || "Permit");
}

function fmtDate(value) {
  if (!value) return "—";
  const d = new Date(value);
  if (Number.isNaN(d.getTime())) return "—";
  return d.toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" });
}

/**
 * Renders a one-page certificate PDF for an issued permit into an in-memory
 * Buffer — called right after a permit is created/updated (see
 * c_permits.js) so every permit gets a real, presentable document instead of
 * relying on staff to source/upload their own scan. Kept intentionally
 * simple (no external logo asset, no barcode/QR) so it has zero extra
 * dependencies; swap in real letterhead assets here later if the client
 * supplies them.
 */
function renderPermitCertificate({ permit, proponentName, applicationNo }) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "A4", margin: 56 });
    const chunks = [];
    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const pageWidth = doc.page.width;
    const contentWidth = pageWidth - doc.page.margins.left - doc.page.margins.right;

    // Decorative border frame.
    doc
      .lineWidth(1.5)
      .strokeColor("#1f2937")
      .rect(24, 24, pageWidth - 48, doc.page.height - 48)
      .stroke();
    doc
      .lineWidth(0.75)
      .strokeColor("#9ca3af")
      .rect(30, 30, pageWidth - 60, doc.page.height - 60)
      .stroke();

    doc.moveDown(2.5);

    // Header / letterhead.
    doc
      .font("Helvetica-Bold")
      .fontSize(11)
      .fillColor("#1f2937")
      .text("3CORE LOCATOR & COMPLIANCE SYSTEM", { align: "center" });
    doc
      .font("Helvetica")
      .fontSize(9)
      .fillColor("#6b7280")
      .text("Clark Development Corporation", { align: "center" });

    doc.moveDown(1.5);
    doc
      .font("Helvetica-Bold")
      .fontSize(22)
      .fillColor("#111827")
      .text("CERTIFICATE OF PERMIT", { align: "center" });
    doc
      .font("Helvetica")
      .fontSize(13)
      .fillColor("#374151")
      .text(permitTypeLabel(permit.permit_type), { align: "center" });

    doc.moveDown(2);
    doc
      .font("Helvetica")
      .fontSize(11)
      .fillColor("#374151")
      .text("This is to certify that", { align: "center" });

    doc.moveDown(0.5);
    doc
      .font("Helvetica-Bold")
      .fontSize(18)
      .fillColor("#111827")
      .text(proponentName || "—", { align: "center" });

    doc.moveDown(0.5);
    doc
      .font("Helvetica")
      .fontSize(11)
      .fillColor("#374151")
      .text(`has been granted the above-named permit, subject to the terms and conditions on record.`, {
        align: "center",
      });

    doc.moveDown(2.5);

    // Details table.
    const rows = [
      ["Permit No.", permit.permit_no || "—"],
      ["Permit Type", permitTypeLabel(permit.permit_type)],
      ["Issuing Authority", permit.issuing_authority || "—"],
      ["Issue Date", fmtDate(permit.issue_date)],
      ["Expiry Date", fmtDate(permit.expiry_date)],
      ...(applicationNo ? [["Linked Application", applicationNo]] : []),
    ];

    const labelWidth = 160;
    const startX = doc.page.margins.left;
    let y = doc.y;
    for (const [label, value] of rows) {
      doc
        .font("Helvetica-Bold")
        .fontSize(10)
        .fillColor("#4b5563")
        .text(label, startX, y, { width: labelWidth });
      doc
        .font("Helvetica")
        .fontSize(10)
        .fillColor("#111827")
        .text(String(value), startX + labelWidth, y, { width: contentWidth - labelWidth });
      y = doc.y + 8;
    }

    doc.y = y + 40;

    // Signature block.
    const sigY = Math.max(doc.y, doc.page.height - 170);
    doc
      .moveTo(startX, sigY)
      .lineTo(startX + 220, sigY)
      .strokeColor("#9ca3af")
      .lineWidth(0.75)
      .stroke();
    doc.font("Helvetica").fontSize(9).fillColor("#6b7280").text("Authorized Signatory", startX, sigY + 4);

    doc
      .font("Helvetica")
      .fontSize(9)
      .fillColor("#9ca3af")
      .text(`Generated by the 3CORE Portal on ${fmtDate(new Date())}`, startX, doc.page.height - 80, {
        width: contentWidth,
        align: "center",
      });

    doc.end();
  });
}

module.exports = { renderPermitCertificate, permitTypeLabel };
